<a href="https://colab.research.google.com/github/Shashank18ram/Data-Science/blob/main/Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df= pd.read_csv('/content/banking_dataset.csv')
df.head()

,customer_age,account_balance,annual_income,loan_amount,loan_duration_months,num_of_credit_cards,credit_card_utilization,monthly_salary,num_of_loans,num_of_defaults,...,insurance_amount,spending_score,digital_transactions_ratio,mobile_banking_usage_hours,branch_visits_per_month,internet_banking_logins,loan_interest_rate,customer_satisfaction_score,risk_factor,bank_profit
0,56,17871.07,1131740.96,409401.23,51,3,0.84,54136.15,2,2,...,128309.65,98.05,0.29,3.63,8,6,6.44,6.68,0.75,494405.22
1,69,54069.27,600090.95,188667.47,31,1,0.51,63632.00,3,2,...,62273.87,0.33,0.89,6.29,6,21,10.82,2.43,0.11,268619.57
2,46,34872.99,756171.18,206035.43,13,3,0.53,63740.55,0,0,...,91142.90,12.02,0.75,5.35,9,5,11.98,3.57,0.79,356441.45
3,32,21554.93,933147.71,318767.03,11,2,0.56,59817.85,1,2,...,115780.27,54.69,0.93,10.51,0,5,6.37,2.89,0.03,373216.34
4,60,37068.54,345408.57,219029.55,29,0,0.17,49422.27,2,1,...,85623.14,95.59,0.69,9.11,3,13,8.60,5.86,0.44,328103.09

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_age                 1000 non-null   int64
 1   account_balance              1000 non-null   float64
 2   annual_income                1000 non-null   float64
 3   loan_amount                  1000 non-null   float64
 4   loan_duration_months         1000 non-null   int64
 5   num_of_credit_cards          1000 non-null   int64
 6   credit_card_utilization      1000 non-null   float64
 7   monthly_salary               1000 non-null   float64
 8   num_of_loans                 1000 non-null   int64
 9   num_of_defaults              1000 non-null   int64
 10  num_of_transactions          1000 non-null   int64
 11  avg_transaction_value        1000 non-null   float64
 12  loan_to_income_ratio         1000 non-null   float64
 13  credit_score                 1000 non-null   float64
 14  investment_value             1000 non-null   float64
 15  savings_account_balance      1000 non-null   float64
 16  fixed_deposit_amount         1000 non-null   float64
 17  num_of_dependents            1000 non-null   int64
 18  customer_tenure_years        1000 non-null   float64
 19  emi_amount                   1000 non-null   float64
 20  house_value                  1000 non-null   float64
 21  insurance_amount             1000 non-null   float64
 22  spending_score               1000 non-null   float64
 23  digital_transactions_ratio   1000 non-null   float64
 24  mobile_banking_usage_hours   1000 non-null   float64
 25  branch_visits_per_month      1000 non-null   int64
 26  internet_banking_logins      1000 non-null   int64
 27  loan_interest_rate           1000 non-null   float64
 28  customer_satisfaction_score  1000 non-null   float64
 29  risk_factor                  1000 non-null   float64
 30  bank_profit                  1000 non-null   float64
dtypes: float64(22), int64(9)
memory usage: 242.3 KB

In [ ]:
from sklearn.preprocessing import StandardScaler
dfScaled=df.copy()

In [ ]:
ss=StandardScaler()
scaled=ss.fit_transform(dfScaled.drop('bank_profit',axis=1))
scaled

array([[ 0.81295917, -1.69176366,  1.74294869, ..., -1.40825527,
         0.5131844 ,  0.89327393],
       [ 1.68057836,  0.14695336, -0.42963904, ...,  1.12371499,
        -1.1784967 , -1.32724698],
       [ 0.1455598 , -0.8281373 ,  0.20818281, ...,  1.79428246,
        -0.72472812,  1.03205648],
       ...,
       [ 1.2133988 , -0.50416973,  0.68654228, ..., -0.83017987,
        -0.27493997, -0.00881269],
       [-0.5885795 ,  0.6741306 , -0.64032328, ...,  0.43580527,
        -0.48988298, -0.59863856],
       [ 0.74621924, -0.43851563,  1.73519873, ...,  0.37799772,
         0.1788286 ,  1.24023032]])

In [ ]:
df_scaled=pd.DataFrame(scaled,columns=dfScaled.drop('bank_profit',axis=1).columns)
df_scaled.head()

,customer_age,account_balance,annual_income,loan_amount,loan_duration_months,num_of_credit_cards,credit_card_utilization,monthly_salary,num_of_loans,num_of_defaults,...,house_value,insurance_amount,spending_score,digital_transactions_ratio,mobile_banking_usage_hours,branch_visits_per_month,internet_banking_logins,loan_interest_rate,customer_satisfaction_score,risk_factor
0,0.812959,-1.691764,1.742949,1.945064,0.642796,0.727699,1.189854,-0.317263,0.418966,1.258777,...,-0.460125,0.760323,1.643617,-0.750647,-0.873148,1.267172,-1.036244,-1.408255,0.513184,0.893274
1,1.680578,0.146953,-0.429639,-0.751237,-0.415392,-0.697764,0.043626,0.282552,1.300999,1.258777,...,0.906162,-0.909685,-1.723542,1.297783,-0.271305,0.550446,0.710234,1.123715,-1.178497,-1.327247
2,0.145560,-0.828137,0.208183,-0.539084,-1.367761,0.727699,0.113095,0.289409,-1.345101,-1.202175,...,1.684177,-0.179603,-1.320737,0.819816,-0.483986,1.625535,-1.152676,1.794282,-0.724728,1.032056
3,-0.788799,-1.504639,0.931397,0.837951,-1.473580,0.014967,0.217297,0.041627,-0.463068,1.258777,...,0.581518,0.443462,0.149552,1.434345,0.683499,-1.599732,-1.152676,-1.448721,-0.995397,-1.604812
4,1.079919,-0.716613,-1.470399,-0.380359,-0.521211,-1.410495,-1.137336,-0.615021,0.418966,0.028301,...,-0.666157,-0.319195,1.558852,0.614973,0.366740,-0.524643,-0.221221,-0.159612,0.186789,-0.182291

In [ ]:
from sklearn.preprocessing import MinMaxScaler
dfMinMax=df.copy()

In [ ]:
mm=MinMaxScaler()
scaled=mm.fit_transform(dfMinMax.drop('bank_profit',axis=1))
scaled

array([[0.74509804, 0.17410113, 0.75536169, ..., 0.07333333, 0.6325167 ,
        0.75      ],
       [1.        , 0.52674635, 0.40052073, ..., 0.80333333, 0.15924276,
        0.11      ],
       [0.54901961, 0.33973494, 0.50469388, ..., 0.99666667, 0.28619154,
        0.79      ],
       ...,
       [0.8627451 , 0.40186827, 0.58282262, ..., 0.24      , 0.41202673,
        0.49      ],
       [0.33333333, 0.62785301, 0.36611043, ..., 0.605     , 0.3518931 ,
        0.32      ],
       [0.7254902 , 0.41445999, 0.75409591, ..., 0.58833333, 0.5389755 ,
        0.85      ]])

In [ ]:
df_Scaled=pd.DataFrame(scaled,columns=dfMinMax.drop('bank_profit',axis=1).columns)
df_Scaled.head()

,customer_age,account_balance,annual_income,loan_amount,loan_duration_months,num_of_credit_cards,credit_card_utilization,monthly_salary,num_of_loans,num_of_defaults,...,house_value,insurance_amount,spending_score,digital_transactions_ratio,mobile_banking_usage_hours,branch_visits_per_month,internet_banking_logins,loan_interest_rate,customer_satisfaction_score,risk_factor
0,0.745098,0.174101,0.755362,0.720454,0.692308,0.75,0.84,0.464366,0.666667,1.0,...,0.486828,0.551377,0.980659,0.29,0.241494,0.888889,0.206897,0.073333,0.632517,0.75
1,1.000000,0.526746,0.400521,0.321579,0.384615,0.25,0.51,0.557751,1.000000,1.0,...,0.699206,0.267606,0.001403,0.89,0.418946,0.666667,0.724138,0.803333,0.159243,0.11
2,0.549020,0.339735,0.504694,0.352963,0.107692,0.75,0.53,0.558818,0.000000,0.0,...,0.820142,0.391663,0.118549,0.75,0.356237,1.000000,0.172414,0.996667,0.286192,0.79
3,0.274510,0.209990,0.622814,0.556674,0.076923,0.50,0.56,0.520241,0.333333,1.0,...,0.648743,0.497536,0.546147,0.93,0.700467,0.000000,0.172414,0.061667,0.210468,0.03
4,0.823529,0.361124,0.230537,0.376444,0.353846,0.00,0.17,0.418008,0.666667,0.5,...,0.454802,0.367943,0.956008,0.69,0.607071,0.333333,0.448276,0.433333,0.541203,0.44

In [ ]:
from sklearn.linear_model import LogisticRegression
#Import the classification  matrices
from sklearn.metrics import classification_report, confusion_matrix,roc_curve,roc_auc_score,accuracy_score

In [ ]:
from sklearn.model_selection import ShuffleSplit,cross_validate
ss = ShuffleSplit(n_splits=10,test_size=0.2,random_state=42)
cv = cross_validate(lr,X,y,cv=ss,scoring='accuracy',return_train_score=True)
print(cv['test_score'].mean())
print(cv['train_score'].mean())

NameError: name 'X' is not defined

In [ ]:
lr.fit(X,y)
y_pred_new = lr.predict(X)
print(accuracy_score(y,y_pred_new))

NameError: name 'X' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression,Lasso
lr=LinearRegression()
cv = cross_validate(lr,dfScaled,df['bank_profit'],cv=ss,scoring='r2',return_train_score=True)
print(cv['test_score'].mean())
print(cv['train_score'].mean())

1.0
1.0

In [ ]:
from sklearn.linear_model import LassoCV
lasso =LassoCV(cv=ss,random_state=42)

lassoCV=lasso.fit(dfScaled,df['bank_profit'])


lassoCV.alpha_

np.float64(18478780.84901518)

In [ ]:
r2_train=lassoCV.score(dfScaled,df['bank_profit'])
print(f'R2 score for the best lasso model:{r2_train:.4F}')

R2 score for the best lasso model:1.0000